### ISSUE TITLE
CCsupport crashes homekit in settings app

### ISSUE THREAD

**Issue by fiatuno49** [opa334/CCSupport#12]
latest version 1.3.5 crashes homekit controller on/of tab in settings/control panel
iphone 6s on ios 14.2
version 1.3.2 and lower does NOT...............for me!

**Comment by opa334** [comment]
show a screen recording, send a crash log from cr4shed

**Comment by fiatuno49** [comment]
TYVM for your help
appreciated

Tony

*************************************



------ Origineel bericht ------
Van: "Lars Fröder" ***@***.***>
Aan: "opa334/CCSupport" ***@***.***>
CC: "fiatuno49" ***@***.***>; "Author" 
***@***.***>
Verzonden: 6/12/2021 12:53:05
Onderwerp: Re: [opa334/CCSupport] CCsupport crashes homekit in settings 
app (Issue #12)

**Comment by opa334** [comment]
This is actually just an issue in the localization code, fixed in 1.3.6.

**Comment by fiatuno49** [comment]
Thanks Lars,

Where can I find version 1.3.6

Must thank you very much

Regards
Tony

************************************************************

------ Origineel bericht ------
Van: "Lars Fröder" ***@***.***>
Aan: "opa334/CCSupport" ***@***.***>
CC: "fiatuno49" ***@***.***>; "Author" 
***@***.***>
Verzonden: 6/12/2021 19:08:36
Onderwerp: Re: [opa334/CCSupport] CCsupport crashes homekit in settings 
app (Issue #12)

**Comment by opa334** [comment]
I submitted it to BigBoss but it will take day or two to become live, then you can update via your package manager.

**Comment by fiatuno49** [comment]
What a service...👍👍👍

Wish there were more devs like you

Tony

------ Origineel bericht ------
Van: "Lars Fröder" ***@***.***>
Aan: "opa334/CCSupport" ***@***.***>
CC: "fiatuno49" ***@***.***>; "Author" 
***@***.***>
Verzonden: 6/12/2021 20:46:52
Onderwerp: Re: [opa334/CCSupport] Localization fallback to english is 
not working (Issue #12)
