### ISSUE TITLE
Crashes Settings app when tapping Control Center iOS 17 iPad 6th gen, crashlog attached

### ISSUE THREAD

**Issue by mailinglists35** [opa334/CCSupport#19]
Hi,

CCSupport causes Settings app to crash when tapping Control Center menu.

Hardware: iPad 6th generation wifi + cellular 128Gb
OS: 17.0
Jailbreak: palera1n [v2.0.0-beta.8](https://github.com/palera1n/palera1n/releases/tag/v2.0.0-beta.8) on Ubuntu Linux 22.04LTS

Reproducer:

palera1n
tap palera1n icon
visit opa334.github.io tap add to sileo
add repo in sileo
install ccsuport
respring
go to Settings - Control Center

on same hardware it worked on 16.2 before doing OTA to 17.0

Attached plist crash logs zipped

**Comment by mailinglists35** [comment]
[Documents.zip](https://github.com/opa334/CCSupport/files/13624151/Documents.zip)

**Comment by opa334** [comment]
To fix this I need syslog output (filter for "Preferences") maybe the "Antoine" app can help?

**Comment by ChrisGleich1AufsMaul** [comment]
Same here on iOS 17, iPad Air 4

Maybe the logs helps :)

[Preferences (Jan 13 5:00 PM).txt](https://github.com/opa334/CCSupport/files/13928748/Preferences.Jan.13.5.00.PM.txt)
[Preferences_2 (Jan 13 5:00 PM).txt](https://github.com/opa334/CCSupport/files/13928749/Preferences_2.Jan.13.5.00.PM.txt)
[Preferences_3 (Jan 13 5:00 PM).txt](https://github.com/opa334/CCSupport/files/13928751/Preferences_3.Jan.13.5.00.PM.txt)

**Comment by opa334** [comment]
Okay I think I know the issue
@mailinglists35 You're supposed to download CCSupport off BigBoss, the one on my repo is outdated
@ChrisGleich1AufsMaul You're most likely also using an outdated build, probably due to this having to have been repackaged to work on RootHide, I do not offer support for RootHide.
