### ISSUE TITLE
Tweak not working on iOS 15.1.1 Xina15

### ISSUE THREAD

**Issue by foxhidden2009** [opa334/CCSupport#21]
Hello opa334,

I'm using your tweak since years and I've just upgraded to an iPhone 13 on iOS 15.1.1, with Xina15 v 1.1.8 and unfortunately I can't make it to work at all...

When I go to Settings -> Control Centre I see that the tweak is enabled because "Show home Controls" is disabled with comment "This option is disabled because CCSupport adds the Home Controls to the Controls below..."

I have tried last version (v1.3.13-2) and also old versions (v1.3.13, v1.3.12, v1.3.11 and v1.3.10-2) but same problem. I didn't see additional CCModules like VPN, Auto Brightness Settings ,etc in the list.

On my iPhone 12 on ios 14.5 it work flawlessly (v 1.3.13-2)

Just one thing when installing the tweak I have the message "Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No Such file or directory) maybe this can do something with my issue ? 

Thanks for your feedback !

**Comment by opa334** [comment]
What do you expect CCSupport to do? It doesn't add modules on it's own, you have to install additional packages

**Comment by foxhidden2009** [comment]
Yes I Know I have also installed Flipconvert and Flipswitch. See my attached pictures. 
I have installed same tweak on the 2 iPhone and I have not the same behavior.
The CCModules that CCSupport add are mostly the "stock" One like surrounded in my first picture below right ?

On my iPhone 12 ios 14.5 :
![IMG_4001](https://github.com/opa334/CCSupport/assets/22011680/c14a6455-a932-4ff6-9a09-ff57daff9324)

On my iPhone 13 ios 15.11 :
![IMG_0027](https://github.com/opa334/CCSupport/assets/22011680/d5aee08c-ff02-4ca6-b565-1bdd5e9dbccb)

Error Message while installing the tweak in Sileo:
![IMG_0057](https://github.com/opa334/CCSupport/assets/22011680/b7f7a515-4e87-4587-a11e-0a2ea56c5340)

**Comment by opa334** [comment]
I don't think Flipswitch / Flipconvert works on Xina, try something else like just the CCModules tweak.

**Comment by foxhidden2009** [comment]
Sorry It work well with CCModules Tweak.
The problem seems to be with Flipconvert, this tweaks bring the CCModules I've searched for...
It seems that I had to contact Dev of the tweak but I doubt Julioverne update it for iOS 15, otherwise it would probably already be done ...
So I have to search others tweaks that will bring the CCModules searched for.
Thanks and sorry for disturbing you !
