### ISSUE TITLE
How would I distribute the tweak?

### ISSUE THREAD

**Issue by MaxHasADHD** [opa334/CCSupport#4]
Sorry if this question has been answered already somewhere. I'm wondering how one would distribute their control center module from the template. Before I installed CCSupport the module I created didn't show up. I assume then that if downloaded in Cydia, it also wouldn't appear unless they install CCSupport (which I don't see on Cydia or on your repo). Is this meant purely for developers for themselves and open sourcing then? Or is there something I need to change / include to have it show up for anyone?

**Comment by opa334** [comment]
You can just upload the deb to a repo, CCSupport will automatically be installed alongside it as it is a dependency of the module. CCSupport is available on the BigBoss repo.
