### ISSUE TITLE
Included Controls not showing up in CC

### ISSUE THREAD

**Issue by 20unkown13** [opa334/CCSupport#5]
Included Controls not showing up in CC after installing CCSupport, after removing I can customize CC again

**Comment by opa334** [comment]
Included Controls?

**Comment by 20unkown13** [comment]
The Controls(buttons in CC) i added in Settings --> Control Centre --> Customize dont show when i open CC only defaults

**Comment by ElChaquiste** [comment]
I have the same trouble, when I download CCSupport from Cydia my buttons go to the default preset.
I reinstalled the jailbreak and tried to install CCSupport first but the problem keeps happening.
I uploaded a video to show you the problem.

[https://www.youtube.com/watch?v=LDunRTRbnFU](url)

As you can see in the video the Screen Record button is in the CC, but after the installation of CCSupport it dissapears.

[https://imgur.com/uAPpVot](url)

I am doing this on an iPhone 6s.

Greetings and thanks for your work!

**Comment by opa334** [comment]
@20unkown13 

Your issue is that CCSupport is not injecting into SpringBoard, please check any tweak configuration tweaks you have to make sure it's not disabled.

@ElChaquiste 

You need to go to Settings -> Customize -> Controls and change the layout there

**Comment by ElChaquiste** [comment]
As you can see in the video I don’t have any tweaks installed just
CCSupport. I don’t even have a CCSupport settings

**Comment by opa334** [comment]
@ElChaquiste I meant Settings -> Control Center -> Customize Controls, sorry

**Comment by ElChaquiste** [comment]
There’s no option inside of customize controls just the default options.

**Comment by opa334** [comment]
Please show a screenshot of the page

**Comment by ElChaquiste** [comment]
I already sent you screenshots in the last email.

**Comment by opa334** [comment]
I have not gotten a single mail about CCSupport in the last month or so, I don't know what you're talking about. My mail is opa334@protonmail.com.

**Comment by ElChaquiste** [comment]
Oh, ok!
I will send it

**Comment by 20unkown13** [comment]
it seems that my problem is fixed now I installed today photon(new update today) and ccsupport and everything works Thx for help
