### ISSUE TITLE
Causing Respring when iCaughtU 12+ is enabled.

### ISSUE THREAD

**Issue by deilsoncso** [opa334/CCSupport#6]
Tiny Volume is causing respring when sliding to increase or decrease the volume when the iCaughtU 12+ is enabled, if you remove the Tiny Volume and add the default toggle Volume, the problem does not occur.

**Comment by opa334** [comment]
CCSupport does not add the tiny volume module, that one is added by CCModules. Also, this sound more like a tweak conflict between CCModules and iCaughtU then anything else.
