### ISSUE TITLE
cant install ccsupport

### ISSUE THREAD

**Issue by jeffw247** [opa334/CCSupport#7]
using 11 pro max ios 13.3, sileo, libhooker

when latest update arrived i tried to install it and wouldn’t install so i uninstalled and now i get this error trying to reinstall. tried restart phone and rejailbreak, same result.

![467466ED-9726-423C-8A26-B2B89513A29D](https://user-images.githubusercontent.com/61130832/96076807-16ae3980-0e63-11eb-9de4-ede80d3ddabc.png)

**Comment by opa334** [comment]
user error, if all else fails try a rootFS restore, can't help you any further
