### ISSUE TITLE
HomeKit CC doesn't work properly 

### ISSUE THREAD

**Issue by iMonZ** [opa334/CCSupport#8]
IOS 14.2
iPhone 7

CC support doesn't support the HomeKit toggles which results of the toggles on the top

![IMG_0003](https://user-images.githubusercontent.com/11319871/103765812-15357d00-501e-11eb-8c51-aa618ee54b1a.PNG)
![IMG_0004](https://user-images.githubusercontent.com/11319871/103765817-1797d700-501e-11eb-9c7c-cc0a5abd2395.PNG)

**Comment by opa334** [comment]
yeah, not fixable due to how apple implemented this. I might try to make a provider for these modules at some point

**Comment by iMonZ** [comment]
Oh that's sad but still thank you

**Comment by opa334** [comment]
fixed in 1.3.3 by making it a seperate module
