### ISSUE TITLE
It seems to change my cc controlled to different things every time I activate it it takes away my screen record button and everything else in a different order 

### ISSUE THREAD

**Issue by stuie1** [opa334/CCSupport#9]
Doesn’t seem to work properly

**Comment by opa334** [comment]
yeah that's normal, setup your layout inside Settings -> Control Center

**Comment by stuie1** [comment]
Lol I know that I trufully do but it doesn’t do a thing like it manifest it’s own layout idk what to say I’m pretty sure I had this layout before but if I change it in setting nothing happens but if I disable ccsuport it just fixes it I see my cc like in the setting but with ccsupoort enabled it skrewed up my cc

From Stuart Bailey Jr

**Comment by stuie1** [comment]
There are 3 pictures there and trust me it’s not prysm I deleted it and nothing changed other then deactivating ccsupport idk what’s happened I mean it’s not new I have jetsam memory crashes every min literally so idk I have rootfs and most of theses glitch’s don’t seem to fix themself my widgets don’t even work but as u can see by the picture I just deactivated just to show u but hell thanks for listening have a good day 
From Stuart Bailey Jr
